# Generated by Django 2.2.5 on 2019-09-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='is_first_login',
            field=models.BooleanField(default=0, verbose_name='Первый вход в систему'),
        ),
    ]
