# Generated by Django 2.2.5 on 2019-09-30 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_worker_is_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='is_online',
            field=models.BooleanField(default=0, verbose_name='Статус на сайте'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='patronymic',
            field=models.CharField(max_length=150, null=True, verbose_name='Отчество'),
        ),
    ]
