# Generated by Django 2.2.5 on 2019-10-24 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0003_auto_20190930_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Работник'),
        ),
    ]
