# Generated by Django 2.2.5 on 2019-11-04 13:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0005_auto_20191103_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Работник'),
        ),
        migrations.AlterField(
            model_name='time',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Работник'),
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_salary', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма премии')),
                ('date_accruals', models.DateField(default=django.utils.timezone.now, verbose_name='Дата начисления')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Работник')),
            ],
        ),
    ]
