# Generated by Django 2.2.5 on 2020-04-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0006_auto_20191104_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtisMakes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(max_length=500, verbose_name='Дисциплина')),
                ('make', models.CharField(max_length=150, verbose_name='Оценка')),
                ('date', models.CharField(max_length=150, verbose_name='Дата')),
                ('teacher', models.CharField(max_length=500, verbose_name='Преподаватель')),
            ],
        ),
    ]
