# Generated by Django 2.2.5 on 2020-04-04 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0007_etismakes'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtisUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='ФИО')),
                ('username', models.CharField(max_length=500, verbose_name='Username Etis')),
                ('password', models.CharField(max_length=500, verbose_name='Password Etis')),
            ],
        ),
        migrations.AddField(
            model_name='etismakes',
            name='trem',
            field=models.CharField(max_length=500, null=True, verbose_name='Триместр'),
        ),
        migrations.AddField(
            model_name='etismakes',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CRM.EtisUsers', verbose_name='Пользователь'),
        ),
    ]
