# Generated by Django 2.2.5 on 2020-04-16 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0009_auto_20200414_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='etisusers',
            name='is_all_makes_in_trem',
            field=models.BooleanField(default=False, verbose_name='Проверка на поток'),
        ),
        migrations.CreateModel(
            name='EtisMakesInTrem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.CharField(max_length=500, verbose_name='Дисциплина')),
                ('tema', models.CharField(max_length=500, verbose_name='Тема')),
                ('type_of_work', models.CharField(max_length=500, verbose_name='Вид работы')),
                ('type_of_control', models.CharField(max_length=500, verbose_name='Вид контроля')),
                ('make', models.CharField(max_length=500, null=True, verbose_name='Оценка')),
                ('passing_score', models.CharField(max_length=500, verbose_name='Проходной балл')),
                ('max_score', models.CharField(max_length=500, verbose_name='Максимальный балл')),
                ('date', models.CharField(max_length=500, null=True, verbose_name='Дата')),
                ('teacher', models.CharField(max_length=500, null=True, verbose_name='Преподаватель')),
                ('trem', models.CharField(max_length=500, verbose_name='Триместр')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='CRM.EtisUsers', verbose_name='Пользователь')),
            ],
        ),
    ]
